### ISSUE TITLE
Bug Fake anons Seed torrent 

### ISSUE THREAD

**Issue by turkishman41** [wy580477/Leech-AIO-APP-EX#62]
Hi brother, does this script hit for the torrent Fake Announcements??!!

For example, i seeded in 10 hours, but show seeded hours time 50 hours !!

**Comment by wy580477** [comment]
Are you using aria2 or qbit?

Aria2 comes from here: https://github.com/P3TERX/Aria2-Pro-Core
qBit comes from here: https://github.com/c0re100/qBittorrent-Enhanced-Edition

**Comment by turkishman41** [comment]
I use qbit , VUE web ui 

If possible, update the code to solve the problem.
It is better to solve the problem of fake anons and let the normal program work.

This code is very good, thank you for your efforts.
Please remove the fake anons, the app will work normally, thank you

**Comment by wy580477** [comment]
> If possible, update the code to solve the problem. It is better to solve the problem of fake anons and let the normal program work.

If there is any problem about announcements ( I doubt there is, it's more likely to be a UI display problem ), it's from [qBittorrent-Enhanced-Edition](https://github.com/c0re100/qBittorrent-Enhanced-Edition).

I suggest you open a issue in qBittorrent-Enhanced-Edition repo.

**Comment by turkishman41** [comment]
![Screenshot_20230115_163945](https://user-images.githubusercontent.com/89349479/212542533-46617aa9-278d-4ae9-901c-40f570eee5c2.jpg)

Everything is clear in the picture.
 I use this script, how can I raise the problem elsewhere?
 If possible, check it, thanks

**Comment by wy580477** [comment]
> Everything in the picture. For 1 day seed , 2000 hours !! 

I think it's just a UI display problem. As long as seeding ratio is right, I think you should be fine.

> I use this script, how can I raise the problem elsewhere?

Because this script gets qbit binary directly from qBittorrent-Enhanced-Edition repo releases.

You can check install.sh by yourself.

https://github.com/wy580477/Leech-AIO-APP-EX/blob/docker/content/install.sh

wget -O - https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/download/release-4.4.5.10/qbittorrent-enhanced-nox_${OS_type2}.zip
