### ISSUE TITLE
Rclone mount

### ISSUE THREAD

**Issue by mohamedkaissi** [wy580477/Leech-AIO-APP-EX#65]
when I want to mount Rclone config , I get this error , This is on koyeb
![Capture](https://user-images.githubusercontent.com/62901183/213708122-5fca5c33-08a5-4a45-8b58-b59efc633534.PNG)
Anthing I can do to fix ?

**Comment by wy580477** [comment]
I haven't found any PaaS platform which can run rclone mount.

To run Rclone mount inside container, you need a privileged container and kernel fuse module.  Unfortunately, PaaS platforms won't let you run privileged container due to security reasons.

If you need to do file operation on Rclone remotes, use Explorer in the Web UI.
